/* eslint-disable @next/next/no-sync-scripts */
import { Inter } from 'next/font/google'
import './globals.css'
import { Script } from 'next'
const inter = Inter({ subsets: ['latin'] })
import ChatBot from '../components/ChatBot/page.jsx'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
        <script src="https://kit.fontawesome.com/a19bb8670a.js" />
        {/* <div id="fb-root"></div> */}
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v18.0&appId=559123289439284" nonce="i71HCiiq"></script>
        <ChatBot />
      </body>
    </html>
  )
}
